backend:
  name: github
  branch: blog
  repo: udit-001/astro-blog
  site_domain: astro.uditmittal.com
  base_url: https://astro.uditmittal.com
  auth_endpoint: oauth
  commit_messages:
    create: "content(cms): create {{collection}}/{{slug}}"
    update: "content(cms): update {{collection}}/{{slug}}"
    delete: "content(cms): delete {{collection}}/{{slug}}"
    publish: "content(cms): publish {{collection}}/{{slug}}"
    unpublish: "content(cms): unpublish {{collection}}/{{slug}}"
    uploadMedia: "content(cms): add media {{path}}"
    deleteMedia: "content(cms): remove media {{path}}"

media_folder: "src/content/blog/images" # Folder where uploaded images will be stored
public_folder: "/content/blog/images" # Public URL of the folder where images are stored  
site_url: "https://astro.uditmittal.com"
display_url: "https://astro.uditmittal.com"
collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Post"
    folder: "src/content/blog"
    slug: "{{slug}}"
    icon: "article"
    path: "{{slug}}/index"
    media_folder: "."
    public_folder: ""
    preview_path: "blog/{{slug}}"
    create: true
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
      - label: Published
        field: draft
        pattern: "^$|false"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          required: false,
          field: { label: "Tag", name: "tag", widget: "string" }
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "bookmarks"
    label: "Bookmarks"
    label_singular: "Bookmark"
    folder: "src/content/bookmarks"
    slug: "{{slug}}"
    icon: "bookmark"
    sortable_fields:
      fields: [title, readDate]
      default:
        field: readDate
        direction: descending
    preview_path: "bookmarks/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Read Date", name: "readDate", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", date_format: "YYYY-MM-DD", time_format: "HH:mm", default: "{{now}}" }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          required: false,
          field: { label: "Tag", name: "tag", widget: "string" }
        }
      - { label: "Body", name: "body", widget: "markdown",  required: false }
  - name: "Prompts"
    label: "Prompts"
    label_singular: "Prompt"
    folder: "src/content/prompts"
    slug: "{{slug}}"
    icon: "chat_paste_go"
    sortable_fields:
      fields: [title, date]
      default:
        field: date
        direction: descending
    preview_path: "prompts/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", date_format: "YYYY-MM-DD", time_format: "HH:mm", default: "{{now}}" }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          required: false,
          field: { label: "Tag", name: "tag", widget: "string" }
        }
      - { label: "Body", name: "body", widget: "markdown",  required: false }
  - name: "videos"
    label: "Videos"
    label_singular: "Video"
    folder: "src/content/videos"
    slug: "{{slug}}"
    icon: "smart_display"
    create: true
    sortable_fields:
      fields: [title, date]
      default:
        field: date
        direction: descending
    preview_path: "videos/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "YouTube URL", name: "url", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", date_format: "YYYY-MM-DD", time_format: "HH:mm", default: "{{now}}" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          required: false,
          field: { label: "Tag", name: "tag", widget: "string" }
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
