backend:
  name: github
  branch: blog
  repo: udit-001/astro-blog
  site_domain: astro.uditmittal.com
  base_url: https://astro.uditmittal.com
  auth_endpoint: oauth

media_folder: "src/content/blog/images" # Folder where uploaded images will be stored
public_folder: "/content/blog/images" # Public URL of the folder where images are stored  

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Post"
    folder: "src/content/blog"
    slug: "{{slug}}"
    path: "{{slug}}/index"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          field: { label: "Tag", name: "tag", widget: "string" }
        }
      - { label: "Body", name: "body", widget: "markdown" }
